In [1]:
!pip install yfinance pandas plotly

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.5.20)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [2]:
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

DOWNLOAD INDIAN STOCKER

In [3]:
ticker = "RELIANCE.NS"

df = yf.download(
    ticker,
    period="5y"
)

df.head()

/tmp/ipykernel_1267/2893586772.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(
[*********************100%***********************]  1 of 1 completed

Price             Close         High         Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2021-06-07  1005.324585  1011.914231  986.187607   993.860485    16336573
2021-06-08   999.547363  1005.211722  992.122745  1004.963523     9674735
2021-06-09   981.674011  1002.435804  973.978571  1001.533141    11409161
2021-06-10   985.284973  1006.498161  982.825123   989.978919    14155653
2021-06-11  1002.375244  1009.101134  987.406313   988.674520    13762778

In [4]:
print(df.shape)

print(df.info())

print(df.describe())

(1238, 5)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1238 entries, 2021-06-07 to 2026-06-05
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   1238 non-null   float64
 1   (High, RELIANCE.NS)    1238 non-null   float64
 2   (Low, RELIANCE.NS)     1238 non-null   float64
 3   (Open, RELIANCE.NS)    1238 non-null   float64
 4   (Volume, RELIANCE.NS)  1238 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.0 KB
None
Price         Close         High          Low         Open        Volume
Ticker  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS   RELIANCE.NS
count   1238.000000  1238.000000  1238.000000  1238.000000  1.238000e+03
mean    1255.911220  1267.710844  1244.876467  1256.483064  1.342839e+07
std      158.112548   158.960336   157.394265   158.076707  7.266766e+06
min      921.823914   932.105133   913.195788   930.293307  0.000000e+00
25%     1133.326324  1143.568427  1121.193659  1132.532732  8.884973e+06
50%     1228.961792  1240.685549  1217.085178  1228.576981  1.177736e+07
75%     1402.149048  1414.478399  1389.121474  1403.063149  1.611188e+07
max     1584.971802  1604.382010  1570.936597  1585.668486  9.146198e+07

In [5]:
df.to_csv("reliance_stock_data.csv")

In [6]:
fig = go.Figure(data=[
    go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close']
    )
])

fig.update_layout(
    title="Reliance Stock Price",
    xaxis_title="Date",
    yaxis_title="Price"
)

fig.show()

In [7]:
fig = go.Figure()

fig.add_bar(
    x=df.index,
    y=df['Volume'],
    name="Volume"
)

fig.update_layout(
    title="Trading Volume"
)

fig.show()

In [8]:
df['SMA20'] = df['Close'].rolling(20).mean()

df['SMA50'] = df['Close'].rolling(50).mean()

In [9]:
fig = go.Figure()

fig.add_scatter(
    x=df.index,
    y=df['Close'],
    name='Close Price'
)

fig.add_scatter(
    x=df.index,
    y=df['SMA20'],
    name='SMA20'
)

fig.add_scatter(
    x=df.index,
    y=df['SMA50'],
    name='SMA50'
)

fig.show()

In [10]:
print(df.head())
print(df.columns)
print(df.dtypes)

Price             Close         High         Low         Open      Volume  \
Ticker      RELIANCE.NS  RELIANCE.NS RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2021-06-07  1005.324585  1011.914231  986.187607   993.860485    16336573
2021-06-08   999.547363  1005.211722  992.122745  1004.963523     9674735
2021-06-09   981.674011  1002.435804  973.978571  1001.533141    11409161
2021-06-10   985.284973  1006.498161  982.825123   989.978919    14155653
2021-06-11  1002.375244  1009.101134  987.406313   988.674520    13762778

Price      SMA20 SMA50
Ticker
Date
2021-06-07   NaN   NaN
2021-06-08   NaN   NaN
2021-06-09   NaN   NaN
2021-06-10   NaN   NaN
2021-06-11   NaN   NaN
MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS'),
            ( 'SMA20',            ''),
            ( 'SMA50',            '')],
           names=['Price', 'Ticker'])
Price   Ticker
Close   RELIANCE.NS    float64
High    RELIANCE.NS    float64
Low     RELIANCE.NS    float64
Open    RELIANCE.NS    float64
Volume  RELIANCE.NS      int64
SMA20                  float64
SMA50                  float64
dtype: object

In [11]:
close = df['Close'].squeeze()

df['SMA20'] = close.rolling(20).mean()
df['SMA50'] = close.rolling(50).mean()

In [12]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df.index,
    y=close,
    mode='lines',
    name='Close Price'
))

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['SMA20'],
    mode='lines',
    name='SMA20'
))

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['SMA50'],
    mode='lines',
    name='SMA50'
))

fig.show()

In [13]:
print(df.columns)
print(df.head())

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS'),
            ( 'SMA20',            ''),
            ( 'SMA50',            '')],
           names=['Price', 'Ticker'])
Price             Close         High         Low         Open      Volume  \
Ticker      RELIANCE.NS  RELIANCE.NS RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2021-06-07  1005.324585  1011.914231  986.187607   993.860485    16336573
2021-06-08   999.547363  1005.211722  992.122745  1004.963523     9674735
2021-06-09   981.674011  1002.435804  973.978571  1001.533141    11409161
2021-06-10   985.284973  1006.498161  982.825123   989.978919    14155653
2021-06-11  1002.375244  1009.101134  987.406313   988.674520    13762778

Price      SMA20 SMA50
Ticker
Date
2021-06-07   NaN   NaN
2021-06-08   NaN   NaN
2021-06-09   NaN   NaN
2021-06-10   NaN   NaN
2021-06-11   NaN   NaN

TECHNICAL ANALYSIS

In [14]:
!pip install ta

Collecting ta
  Downloading ta-0.11.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ta) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ta) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ta) (1.17.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.11.0-py3-none-any.whl size=29412 sha256=c36d4f9cf8d4d93e8fc92cdad5d4f3cabbd99c057da87dd95e3b7d1e2e657ff7
  Stored in directory: /root/.cache/pip/wheels/5c/a1/5f/c6b85a7d9452057be4ce68a8e45d77ba34234a6d46581777c6
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.11.0

In [15]:
import ta

In [17]:
close = df['Close'].squeeze()

In [18]:
print(type(close))
print(close.shape)

<class 'pandas.core.series.Series'>
(1238,)

In [20]:
df['RSI'] = ta.momentum.RSIIndicator(
    close=close,
    window=14
).rsi()

In [21]:
print(type(df['Close']))
print(df['Close'].shape)

<class 'pandas.core.frame.DataFrame'>
(1238, 1)

In [22]:
print(df.columns)

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS'),
            ( 'SMA20',            ''),
            ( 'SMA50',            ''),
            (   'RSI',            '')],
           names=['Price', 'Ticker'])

In [23]:
df_clean = pd.DataFrame(index=df.index)

df_clean['Close'] = close
df_clean['High'] = df['High'].squeeze()
df_clean['Low'] = df['Low'].squeeze()
df_clean['Open'] = df['Open'].squeeze()
df_clean['Volume'] = df['Volume'].squeeze()

df = df_clean

In [24]:
print(df.columns)
print(type(df['Close']))

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')
<class 'pandas.core.series.Series'>

In [25]:
df['SMA20'] = df['Close'].rolling(20).mean()
df['SMA50'] = df['Close'].rolling(50).mean()

df['RSI'] = ta.momentum.RSIIndicator(
    close=df['Close'],
    window=14
).rsi()

In [26]:
macd = ta.trend.MACD(df['Close'])

df['MACD'] = macd.macd()
df['MACD_Signal'] = macd.macd_signal()
df['MACD_Hist'] = macd.macd_diff()

In [27]:
df.tail()

,Close,High,Low,Open,Volume,SMA20,SMA50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,
2026-06-01,1313.924927,1329.353591,1312.431830,1326.367398,10700603,1362.201715,1363.320564,38.181920,-13.479186,-9.055959,-4.423227
2026-06-02,1308.549805,1321.689127,1294.315690,1301.681536,23302785,1354.786005,1361.459170,37.063949,-15.145247,-10.273816,-4.871431
2026-06-03,1307.156250,1317.906594,1295.012446,1308.948015,20012293,1348.579700,1360.033760,36.763404,-16.389137,-11.496881,-4.892257
2026-06-04,1297.699951,1305.165434,1287.148760,1295.012426,23474327,1341.985193,1357.829949,34.706787,-17.931273,-12.783759,-5.147514
2026-06-05,1291.000000,1306.000000,1288.000000,1304.500000,17785223,1335.105457,1355.623530,33.285983,-19.469623,-14.120932,-5.348691

In [28]:
df['Signal'] = 0

df.loc[df['SMA20'] > df['SMA50'], 'Signal'] = 1
df.loc[df['SMA20'] < df['SMA50'], 'Signal'] = -1

In [29]:
df['RSI_Signal'] = 0

df.loc[df['RSI'] < 30, 'RSI_Signal'] = 1
df.loc[df['RSI'] > 70, 'RSI_Signal'] = -1

In [30]:
df['Final_Signal'] = (
    df['Signal'] +
    df['RSI_Signal']
)

In [31]:
latest = df.iloc[-1]

print("Current Price:", latest['Close'])
print("RSI:", round(latest['RSI'], 2))
print("Signal:", latest['Final_Signal'])

Current Price: 1291.0
RSI: 33.29
Signal: -1.0

In [32]:
buy = df[df['Signal'] == 1]
sell = df[df['Signal'] == -1]

In [33]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['Close'],
    name='Close'
))

fig.add_trace(go.Scatter(
    x=buy.index,
    y=buy['Close'],
    mode='markers',
    name='Buy'
))

fig.add_trace(go.Scatter(
    x=sell.index,
    y=sell['Close'],
    mode='markers',
    name='Sell'
))

fig.show()

In [34]:
!pip install feedparser transformers torch pandas

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.9.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 3.0 MB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=30bd89309eabd4256899e9c779d9bb55e326576eda16ab473117dc49fb3c0eca
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

In [35]:
import feedparser
import pandas as pd

url = "https://news.google.com/rss/search?q=Reliance+Industries"

feed = feedparser.parse(url)

news = []

for entry in feed.entries:
    news.append({
        "title": entry.title,
        "published": entry.published
    })

news_df = pd.DataFrame(news)

news_df.head()

,title,published
0,Breakingviews - Reliance hiring slump is calm ...,"Thu, 04 Jun 2026 13:47:59 GMT"
1,"Reliance Industries slides Friday, underperfor...","Fri, 05 Jun 2026 10:30:00 GMT"
2,Reliance Traders Said to Game Plan in Case RBI...,"Thu, 04 Jun 2026 08:50:27 GMT"
3,Reliance Industries dividend alert! Last date ...,"Fri, 05 Jun 2026 15:25:08 GMT"
4,Ms. Isha M. Ambani — Promoter Director on the ...,"Sat, 06 Jun 2026 06:35:29 GMT"

In [36]:
!pip install transformers torchv

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.9.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [37]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:


The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [38]:
news_df["sentiment"] = news_df["title"].apply(
    lambda x: sentiment_model(x)[0]["label"]
)

news_df.head()

,title,published,sentiment
0,Breakingviews - Reliance hiring slump is calm ...,"Thu, 04 Jun 2026 13:47:59 GMT",neutral
1,"Reliance Industries slides Friday, underperfor...","Fri, 05 Jun 2026 10:30:00 GMT",positive
2,Reliance Traders Said to Game Plan in Case RBI...,"Thu, 04 Jun 2026 08:50:27 GMT",neutral
3,Reliance Industries dividend alert! Last date ...,"Fri, 05 Jun 2026 15:25:08 GMT",neutral
4,Ms. Isha M. Ambani — Promoter Director on the ...,"Sat, 06 Jun 2026 06:35:29 GMT",neutral

In [39]:
news_df["sentiment"].value_counts()

sentiment
neutral     56
positive    26
negative    18
Name: count, dtype: int64

In [40]:
score_map = {
    "positive": 1,
    "neutral": 0,
    "negative": -1
}

news_df["score"] = news_df["sentiment"].map(score_map)

overall_sentiment = news_df["score"].mean()

print("Market Sentiment:", overall_sentiment)

Market Sentiment: 0.08

In [41]:
!pip install numpy pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [42]:
df['Returns'] = df['Close'].pct_change()

In [43]:
annual_return = df['Returns'].mean() * 252

print("Annual Return:", annual_return)

Annual Return: 0.07582591148627357

In [44]:
volatility = df['Returns'].std() * (252 ** 0.5)

print("Volatility:", volatility)

Volatility: 0.22318091104744417

In [45]:
risk_free_rate = 0.06

sharpe_ratio = (
    annual_return - risk_free_rate
) / volatility

print("Sharpe Ratio:", sharpe_ratio)

Sharpe Ratio: 0.0709106859184264

In [46]:
cumulative = (1 + df['Returns']).cumprod()

rolling_max = cumulative.cummax()

drawdown = (
    cumulative - rolling_max
) / rolling_max

max_drawdown = drawdown.min()

print("Max Drawdown:", max_drawdown)

Max Drawdown: -0.2717575121316011

In [47]:
import plotly.express as px

fig = px.line(
    drawdown,
    title="Portfolio Drawdown"
)

fig.show()

In [48]:
metrics = {
    "Annual Return": annual_return,
    "Volatility": volatility,
    "Sharpe Ratio": sharpe_ratio,
    "Max Drawdown": max_drawdown
}

print(metrics)

{'Annual Return': np.float64(0.07582591148627357), 'Volatility': 0.22318091104744417, 'Sharpe Ratio': np.float64(0.0709106859184264), 'Max Drawdown': -0.2717575121316011}

In [49]:
!pip install xgboost scikit-learn

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [50]:
df['Target'] = df['Close'].shift(-1)

df = df.dropna()

In [51]:
features = [
    'Open',
    'High',
    'Low',
    'Close',
    'Volume',
    'SMA20',
    'SMA50',
    'RSI',
    'MACD'
]

X = df[features]
y = df['Target']

In [52]:
split = int(len(df) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

In [53]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [54]:
predictions = model.predict(X_test)

In [55]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, predictions)
rmse = mean_squared_error(
    y_test,
    predictions
) ** 0.5

r2 = r2_score(y_test, predictions)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 21.241367885044642
RMSE: 27.95990292461378
R2  : 0.843890641971275

In [56]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    y=y_test.values,
    name="Actual"
))

fig.add_trace(go.Scatter(
    y=predictions,
    name="Predicted"
))

fig.update_layout(
    title="Actual vs Predicted Close Price"
)

fig.show()

In [57]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": features,
    "Importance": model.feature_importances_
})

importance.sort_values(
    "Importance",
    ascending=False
)

  Feature  Importance
1    High    0.791054
3   Close    0.169722
2     Low    0.030658
0    Open    0.002786
5   SMA20    0.001273
8    MACD    0.001251
7     RSI    0.001165
6   SMA50    0.001122
4  Volume    0.000970

In [58]:
results = {
    "MAE": mae,
    "RMSE": rmse,
    "R2 Score": r2
}

print(results)

{'MAE': 21.241367885044642, 'RMSE': 27.95990292461378, 'R2 Score': 0.843890641971275}

In [59]:
import plotly.express as px

importance = pd.DataFrame({
    "Feature": features,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

fig = px.bar(
    importance,
    x="Importance",
    y="Feature",
    orientation="h",
    title="Feature Importance"
)

fig.show()

In [60]:
print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 21.241367885044642
RMSE: 27.95990292461378
R2  : 0.843890641971275